# Generated by Django 4.2.1 on 2023-05-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='direccion_destino',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='numero_seguimiento',
        ),
        migrations.AddField(
            model_name='paquete',
            name='content',
            field=models.CharField(default='blank', max_length=500),
        ),
        migrations.AddField(
            model_name='paquete',
            name='content2',
            field=models.CharField(default='blank', max_length=500),
        ),
        migrations.AddField(
            model_name='paquete',
            name='title',
            field=models.CharField(default='blank title', max_length=255),
        ),
    ]
