# Generated by Django 4.2.1 on 2023-05-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0002_remove_paquete_destinatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('PREPARACION', 'En preparación en centro de distribución'), ('TRANSITO', 'En tránsito hacia el destino'), ('ENTREGADO', 'Recepcionado por el destinatario')], default='PREPARACION', max_length=20)),
                ('destinatario', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
