# Generated by Django 4.2.1 on 2023-05-23 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0003_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha_hora_cambio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='destinatario',
            new_name='direccion_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='direccion_destino',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion_origen',
            field=models.CharField(default='CD de distribución', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_hora_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='nombre_destinatario',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estadoenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_restful.envio'),
        ),
        migrations.AddField(
            model_name='envio',
            name='sucursal_destino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_restful.sucursal'),
        ),
    ]
