# Generated by Django 4.2.1 on 2023-05-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0005_alter_envio_direccion_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='sucursal_destino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_restful.sucursal'),
        ),
    ]
