# Generated by Django 4.2.1 on 2023-05-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0006_alter_envio_sucursal_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoenvio',
            name='envio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_restful.envio'),
        ),
    ]
