# Generated by Django 4.2.1 on 2023-05-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0007_alter_estadoenvio_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='direccion_destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='envio',
            name='nombre_destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='envio',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_restful.sucursal'),
        ),
        migrations.AlterField(
            model_name='estadoenvio',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_restful.envio'),
        ),
    ]
