# Generated by Django 4.2.1 on 2023-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0008_alter_envio_direccion_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='numero_seguimiento',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
