# Generated by Django 4.2.1 on 2023-05-23 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0009_alter_envio_numero_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
