# Generated by Django 4.2.1 on 2023-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0011_envio_address_attributes_envio_branch_office_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='height',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='length',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='width',
            field=models.FloatField(default=1),
        ),
    ]
