# Generated by Django 4.2.1 on 2023-05-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0012_alter_envio_height_alter_envio_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='branch_office_id',
        ),
    ]
