# Generated by Django 4.2.1 on 2023-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0013_remove_envio_branch_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='comuna_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
