# Generated by Django 4.2.1 on 2023-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0014_envio_comuna_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='comuna_destino',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
