# Generated by Django 4.2.1 on 2023-05-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0016_alter_envio_comuna_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
